name = "meta-refinement-types"
version = "0.1.0"
defaultTargets = ["meta-refinement-types"]

[[lean_lib]]
name = "LeanFixpoint"

[[lean_exe]]
name = "meta-refinement-types"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"