#!/usr/bin/env python3
"""Generate the RQ2 LaTeX table from eval/rq3_results.json (3-config schema).

Three configs all run *only* the acyclic-κ elimination then `all_goals sorry`:
  zap   = fusion        (deterministic proof term)
  grind = fusion_grind  (κ-head clauses by grind)   — may FAIL
  aesop = fusion_aesop  (κ-head clauses by aesop)    — may FAIL

Headline metric: `elim_hb` = Σ of the variant's `[phase]` heartbeats, i.e. the
pure acyclic-κ elimination cost (thousands of Lean heartbeats, deterministic).
A FAILed variant errored out trying to discharge a κ-head clause; that is a data
point (rendered `fail`). Figures are deferred (regenerate separately).

Writes eval/rq3_table.tex (tab:rq3 + tab:rq3-term). Run: python3 scripts/rq3_table.py
"""
from __future__ import annotations

import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "eval" / "rq3_results.json"
CFGS = ("zap", "grind", "aesop")


def geomean(xs):
    xs = [x for x in xs if x and x > 0]
    return math.exp(sum(map(math.log, xs)) / len(xs)) if xs else float("nan")


def load():
    data = json.loads(DATA.read_text())
    rows = []
    for b, c in data.items():
        r = dict(bench=b,
                 grp=("FX" if c.get("group") == "FluxRS" else "LF"),
                 nac=c.get("n_acyclic"), ncy=c.get("n_cyclic"),
                 bucket=("both" if (c.get("n_cyclic") or 0) > 0 else "acyclic_only"))
        for k in CFGS:
            d = c.get(k, {})
            ok = d.get("status") == "ok"
            r[k] = dict(ok=ok, elim=d.get("elim_hb"), hb=d.get("hb"),
                        depth=d.get("depth"), nconst=d.get("nconst"),
                        kerus=d.get("kerus"))
        rows.append(r)
    return rows


def esc(s):
    return s.replace("_", "\\_")


def fmt(x):
    return f"{x:,}".replace(",", "\\,") if isinstance(x, int) else str(x)


def cell_elim(c, base):
    """Heartbeat cell: raw elim hb if ok, else 'fail'. Append ×slowdown vs base."""
    if not c["ok"] or c["elim"] is None:
        return r"\textit{fail}"
    s = fmt(c["elim"])
    if base and c["elim"] and base != c["elim"]:
        s += f"\\,({c['elim'] / base:.0f}$\\times$)"
    return s


def latex_table(rows):
    order = sorted(rows, key=lambda r: (r["bucket"] != "acyclic_only", r["bench"].lower()))
    acy = [r for r in order if r["bucket"] == "acyclic_only"]
    bot = [r for r in order if r["bucket"] == "both"]

    FAIL = r"\textit{fail}"

    def block(rs):
        out = []
        for r in rs:
            base = r["zap"]["elim"] if r["zap"]["ok"] else None
            zc = fmt(r["zap"]["elim"]) if r["zap"]["ok"] else FAIL
            gc = cell_elim(r["grind"], base)
            ac = cell_elim(r["aesop"], base)
            out.append(
                f"\\quad {esc(r['bench'])} & {r['grp']} & {r['nac']} & {r['ncy']}"
                f" & {zc} & {gc} & {ac} \\\\")
        return out

    # success counts + geomean slowdown over jointly-ok cases
    def n_ok(k):
        return sum(1 for r in rows if r[k]["ok"])
    def gm_slow(k):
        return geomean([r[k]["elim"] / r["zap"]["elim"] for r in rows
                        if r[k]["ok"] and r["zap"]["ok"] and r["zap"]["elim"]])

    L = [
        r"% Auto-generated by scripts/rq3_table.py — do not edit by hand.",
        r"\begin{table}[t]", r"\centering", r"\small",
        r"\caption{RQ2: cost of \emph{acyclic-$\kappa$ elimination} only "
        r"(then \lean{sorry}), in thousands of Lean heartbeats (deterministic). "
        r"\textsc{Zap} (\lean{fusion}) builds the proof term; \lean{fusion\_grind}"
        r"/\lean{fusion\_aesop} discharge each $\kappa$-head clause by search. "
        r"\textit{fail} = the search variant errored on a $\kappa$-head clause. "
        r"Parenthesised $\times$ is the slowdown vs.\ \textsc{Zap}. "
        r"(LF: Liquid-fixpoint, FX: FluxRS.)}",
        r"\label{tab:rq3}",
        r"\begin{tabular}{llrrrrr}", r"\toprule",
        r"Benchmark & Src & $\kappa_{\text{acy}}$ & $\kappa_{\text{cut}}$"
        r" & \textsc{Zap} & \lean{fusion\_grind} & \lean{fusion\_aesop} \\",
        r"\midrule",
        r"\multicolumn{7}{l}{\emph{acyclic-only}}\\",
    ]
    L += block(acy)
    L += [r"\midrule", r"\multicolumn{7}{l}{\emph{acyclic + cut}}\\"]
    L += block(bot)
    L += [
        r"\midrule",
        f"\\multicolumn{{4}}{{l}}{{solved / {len(rows)}}} & {n_ok('zap')}"
        f" & {n_ok('grind')} & {n_ok('aesop')} \\\\",
        f"\\multicolumn{{4}}{{l}}{{geomean slowdown vs.\\ \\textsc{{Zap}}"
        f" (solved only)}} & 1.0$\\times$ & {gm_slow('grind'):.0f}$\\times$"
        f" & {gm_slow('aesop'):.0f}$\\times$ \\\\",
        r"\bottomrule", r"\end{tabular}", r"\end{table}", "",
        # ── secondary: proof-term shape (ok configs only) ──
        r"% Proof-term shape of the elimination bridge (ok configs; residual is sorry'd).",
        r"\begin{table}[t]", r"\centering", r"\small",
        r"\caption{Elimination proof-term shape: expression-tree depth, \#distinct"
        r" constants, and kernel re-check time ($\mu$s). \textit{fail} = variant"
        r" errored. The deterministic \textsc{Zap} term is built without search;"
        r" the residual VC is left \lean{sorry} in all three.}",
        r"\label{tab:rq3-term}",
        r"\begin{tabular}{lrrrrrrrrr}", r"\toprule",
        r" & \multicolumn{3}{c}{depth} & \multicolumn{3}{c}{\#consts}"
        r" & \multicolumn{3}{c}{kernel ($\mu$s)} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}",
        r"Benchmark & Z & g & a & Z & g & a & Z & g & a \\", r"\midrule",
    ]
    def tcell(c, key):
        return fmt(c[key]) if c["ok"] and c[key] is not None else r"\textit{f}"
    for r in order:
        L.append(
            f"{esc(r['bench'])}"
            f" & {tcell(r['zap'],'depth')} & {tcell(r['grind'],'depth')} & {tcell(r['aesop'],'depth')}"
            f" & {tcell(r['zap'],'nconst')} & {tcell(r['grind'],'nconst')} & {tcell(r['aesop'],'nconst')}"
            f" & {tcell(r['zap'],'kerus')} & {tcell(r['grind'],'kerus')} & {tcell(r['aesop'],'kerus')} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

    out = REPO / "eval" / "rq3_table.tex"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}")
    # console summary
    print(f"\nsolved: zap {n_ok('zap')}/{len(rows)}  "
          f"grind {n_ok('grind')}/{len(rows)}  aesop {n_ok('aesop')}/{len(rows)}")
    print(f"geomean slowdown vs Zap (solved only): "
          f"grind {gm_slow('grind'):.1f}×  aesop {gm_slow('aesop'):.1f}×")


if __name__ == "__main__":
    latex_table(load())
