name = "lean_proofs"
version = "0.1.0"
defaultTargets = ["LeanProofs"]

[[lean_lib]]
name = "LeanProofs"

[[require]]
name = "LeanFixpoint"
git = "https://github.com/jam-khan/lean-fixpoint"
rev = "main"
